### ISSUE TITLE
Disable Cloud Watch alarms

### ISSUE THREAD

**Issue by JPMallow** [ubergeek42/domjudge-aws#3]
When I look through the scripts I have noticed that there are some cloud watch alarms being set. Is there any possibility to disable the cloud watch alarm being created? May be with any flag in setup.sh file.

**Comment by ubergeek42** [comment]
Some alarms are necessary for autoscaling actions to occur. Others are set to notify the arn you configure, so you can just set that to something that doesn't actually notify you.

If you just don't want them created at all that is a bit trickier. Terraform doesn't support conditional statements, so it's harder to make a variable that will only create the alarms when necessary.  I'd suggest just commenting out the alarms you aren't interested in in the terraform files themselves.

**Comment by JPMallow** [comment]
ok thanks
